# TODO: Add healthcheck to services
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.3
    container_name: needle-${ENVIRONMENT}-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
      - http.port=9200
    ports:
      - "${ES_HOST}:${ES_PORT}:9200" # TODO: Currently served on localhost to prevent security issues. Add auth and serve on all interfaces in the future.
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200/_cluster/health?pretty | grep -q 'status.*\\(green\\|yellow\\)'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.3
    container_name: needle-${ENVIRONMENT}-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: needle-${ENVIRONMENT}-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_HOST}:${MINIO_PORT}:9000"
      - "${MINIO_HOST}:${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - miniodata:/data
    command: server /data --address ":9000" --console-address ":9001"
    restart: unless-stopped

volumes:
  esdata:
  miniodata:

networks:
  default:
    name: needle-${ENVIRONMENT}-network
