services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.3
    container_name: bq-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
      - http.port=9200
    ports:
      - "${ES_HOST}:${ES_PORT}:9200" # TODO: Currently served on localhost to prevent security issues. Add auth and serve on all interfaces in the future.
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  esdata:
