[build-system]
requires = ["setuptools>=82.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "needle"
version = "0.3.0"
description = "Intelligent QA for businesses."
requires-python = ">=3.12"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [ { name = "Arman Rezaei", email = "mani@argoman.io" } ]
dynamic = ["dependencies", "optional-dependencies"]

[project.urls]
Homepage = "https://github.com/fadelights/needle"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt", "requirements-doc.txt"]}
optional-dependencies.dev = {file = ["requirements-dev.txt"]}

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"
markers = [
    "integration",
]
asyncio_mode = "auto"
addopts = [
    "--import-mode=importlib",
]

[tool.black]
line-length = 100
