[build-system]
requires = ["setuptools>=82.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "balequeue"
version = "0.2.0"
description = "Intelligent QA for businesses."
requires-python = ">=3.12"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [ { name = "Arman Rezaei", email = "mani@argoman.io" } ]
dynamic = ["dependencies", "optional-dependencies"]

[project.urls]
Homepage = "https://git.argoman.io/mlops/balequeue"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies.dev = {file = ["requirements-dev.txt"]}
optional-dependencies.doc = {file = ["requirements-doc.txt"]}

[tool.pytest.ini_options]
testpaths = "tests"
asyncio_mode = "auto"
addopts = [
    "--import-mode=importlib",
]
